theme: minima
title: IARA GONÇALVES DOS SANTOS
author: Iara Santos
email: iaragstos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  +55 98937 7661	iara.santos@ufv.br	linkedin.com/in/iara-gonçalves-dos-santos-631931118

# social links
github_username:  IaraStos
